# Generated by Django 4.2.1 on 2023-05-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_slideritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderItem',
        ),
    ]
