# Generated by Django 4.2.1 on 2023-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_slide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='category',
            field=models.CharField(choices=[('A', 'Slide A'), ('B', 'Slide B')], default='A', max_length=1),
        ),
    ]
