# Generated by Django 4.2.1 on 2023-05-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_slide_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='category',
        ),
    ]
