# Generated by Django 4.2.1 on 2023-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_slide_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='banner/')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
    ]
