# Generated by Django 4.2.1 on 2023-05-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
