# Generated by Django 4.2.1 on 2023-06-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_address_shippingaddress_street_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
