# Generated by Django 4.2.1 on 2023-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_shippingaddress_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='save_info',
            field=models.BooleanField(default=False),
        ),
    ]
