# Generated by Django 4.2.1 on 2023-06-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_shippingaddress_customer_myorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrder',
        ),
    ]
