# Generated by Django 4.2.1 on 2023-06-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_myorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('CHUA_GIAO', 'Chưa giao'), ('DA_GIAO', 'Đã giao')], default='CHUA_GIAO', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
