# Generated by Django 4.2.1 on 2023-06-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Chưa giao', 'Chưa giao'), ('Đã giao', 'Đã giao')], default='Chưa giao', max_length=20),
        ),
    ]
